---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  # ----------------------- OPS -----------------------
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, "2", --sequence, "4", --offset, "2", --width, "150", --preserve-quotes]
        exclude: ^.github/dependabot.yaml
#        exclude: (sops\.yaml)$
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        args:
          - --ignore
          - DL3025
          - --ignore
          - DL3018
          - --ignore
          - DL3027
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_trivy
        args:
          - >
            --args=
              --skip-files="**/.terraform/**/*"
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yaml
  # ------------------------- PYTHON ------------------------
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix", "--ignore=E402,E501"]
        exclude: ^migrations/
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
        args: ["-C", "./backend"]
      - id: poetry-lock
        args: ["-C", "./backend"]
      - id: poetry-export
        args: ["-C", "./backend", "--without-hashes", "-f", "requirements.txt", "-o", "./backend/requirements.txt"]
#  - repo: local
#    hooks:
#     - id: mypy
#       name: mypy
#       entry: "poetry run mypy $PROJECT"
#       language: system
#       types: [python]
#       pass_filenames: false
#       require_serial: true
