"""add operation_name

Revision ID: 284162ba6c5a
Revises: c73158f9ec9c
Create Date: 2024-08-13 17:11:46.890888

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '284162ba6c5a'
down_revision = 'c73158f9ec9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foo', sa.Column('operation_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foo', 'operation_name')
    # ### end Alembic commands ###
