"""update schema

Revision ID: c73158f9ec9c
Revises: e4569bf81c29
Create Date: 2024-08-13 15:57:45.080282

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c73158f9ec9c'
down_revision = 'e4569bf81c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foo', sa.Column('gcs_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('foo', sa.Column('transcription', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('foo', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foo', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('foo', 'transcription')
    op.drop_column('foo', 'gcs_uri')
    # ### end Alembic commands ###
