"""mark transcript as optional

Revision ID: da059e6a3c68
Revises: 399c1bf6ebeb
Create Date: 2024-08-13 17:43:17.124911

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'da059e6a3c68'
down_revision = '399c1bf6ebeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foo', 'transcript',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foo', 'transcript',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
