"""remove is_done in table

Revision ID: ddaaaca1bb37
Revises: da059e6a3c68
Create Date: 2024-08-13 18:05:28.789368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ddaaaca1bb37'
down_revision = 'da059e6a3c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foo', 'is_done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foo', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
